---
- include_tasks: ubuntu-16.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- include_tasks: ubuntu-18.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: "Put a line in ~/.profile to add fleur to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ fleur_topdir }}/build"

- include_role:
    name: release_notes
  vars:
    section: "fleur"
    option: "version"
    value: "{{ fleur_version }} {{ fleur_release }}"
  when: release_notes is defined and release_notes

- include_role:
    name: release_notes
  vars:
    section: "fleur"
    option: "usage"
    value: >-
      fleur is compiled and installed in {{ fleur_topdir }}. 
      The folder with executables is added to the path, so simply run 'fleur'
  when: release_notes is defined and release_notes
