---
dependency:
  name: galaxy
  requirements_file: molecule/default/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -x 503 -x 305
platforms:
  - name: instance
    image: "${DOCKER_IMAGE:-marvelnccr/ubuntu-docker-base}:${DOCKER_IMAGE_VERSION:-latest}"
    command: "${DOCKER_COMMAND:-sleep infinity}"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 'ANSIBLE0013'
        - 'ANSIBLE0016'
  playbooks:
    converge: converge.yml
